[book]
title = "Manuel rust-config-tree"
authors = ["developerworks"]
description = "Manuel français de rust-config-tree."
language = "fr"
src = "."

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/developerworks/rust-config-tree"
edit-url-template = "https://github.com/developerworks/rust-config-tree/edit/main/manual/fr/{path}"
site-url = "/rust-config-tree/fr/"
additional-css = ["../en/theme/left-aligned.css"]

